"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { CheckCircle2, Download, Flag, Plus, RefreshCw, ShieldAlert, XCircle } from "lucide-react";
import type { CustomerSuccessDashboardData, CustomerSuccessSummary, ProjectStatus, SuccessProject } from "@/lib/customer-success/types";
import { duration, money } from "@/lib/customer-success/format";
import { AdminBarChart, AdminLineChart } from "./admin-charts";

const defaultProjectForm = {
  workspaceId: "",
  userId: "",
  clientName: "",
  projectTitle: "",
  leadSource: "",
  projectCategory: "",
  projectDescription: "",
  dateWon: new Date().toISOString().slice(0, 10),
  currency: "USD",
  projectValue: "0",
  isRecurringRevenue: false,
  notes: "",
  invoiceUrl: ""
};

export function CustomerSuccessDashboard({ data, canManage }: { data: CustomerSuccessDashboardData; canManage: boolean }) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [range, setRange] = useState("last_30_days");
  const [statusFilter, setStatusFilter] = useState("all");
  const [customerFilter, setCustomerFilter] = useState("");
  const [projectFormOpen, setProjectFormOpen] = useState(false);
  const [form, setForm] = useState(defaultProjectForm);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  const filteredProjects = useMemo(() => {
    const since = rangeDate(range);
    return data.projects.filter(project => {
      const matchesStatus = statusFilter === "all" || project.status === statusFilter;
      const matchesCustomer = !customerFilter || project.customerName.toLowerCase().includes(customerFilter.toLowerCase()) || project.customerEmail.toLowerCase().includes(customerFilter.toLowerCase());
      const matchesRange = !since || new Date(project.dateWon) >= since;
      return matchesStatus && matchesCustomer && matchesRange;
    });
  }, [customerFilter, data.projects, range, statusFilter]);

  async function submitProject() {
    setMessage("");
    setError("");
    const response = await fetch("/api/admin/customer-success", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        ...form,
        projectValue: Number(form.projectValue || 0)
      })
    });
    const result = await response.json().catch(() => ({}));
    if (!response.ok) {
      setError(String(result.error || "Could not create project report."));
      return;
    }
    setMessage("Project report created and queued for review.");
    setProjectFormOpen(false);
    setForm(defaultProjectForm);
    router.refresh();
  }

  async function reviewProject(project: SuccessProject, status: ProjectStatus) {
    setMessage("");
    setError("");
    startTransition(async () => {
      const response = await fetch(`/api/admin/customer-success/projects/${project.id}`, {
        method: "PATCH",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ status })
      });
      const result = await response.json().catch(() => ({}));
      if (!response.ok) {
        setError(String(result.error || "Could not update project status."));
        return;
      }
      setMessage(status === "verified" ? "Project verified. Revenue analytics updated." : "Project rejected and excluded from verified revenue.");
      router.refresh();
    });
  }

  return (
    <div className="space-y-6">
      <section className="overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-slate-900 via-slate-950 to-emerald-950">
        <div className="border-b border-white/10 px-6 py-5">
          <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
            <div>
              <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.24em] text-emerald-300">
                <Flag size={16} />
                Customer Success & BI
              </div>
              <h1 className="mt-3 text-3xl font-semibold tracking-tight text-white">Success Tracking</h1>
              <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">
                Track verified customer revenue, project wins, product usage, daily progress, feature adoption, health scores, and business value generated by the platform.
              </p>
            </div>
            <div className="flex flex-wrap gap-2">
              <ExportButton format="csv" />
              <ExportButton format="xls" />
              <ExportButton format="pdf" />
              {canManage ? (
                <button type="button" onClick={() => setProjectFormOpen(true)} className="studio-button bg-emerald-500 text-slate-950 hover:bg-emerald-400">
                  <Plus size={16} /> Report New Project
                </button>
              ) : null}
            </div>
          </div>
        </div>
        <div className="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-4">
          {data.metrics.map(metric => (
            <div key={metric.label} className="rounded-2xl border border-white/10 bg-white/[0.05] p-4">
              <div className="text-xs text-slate-400">{metric.label}</div>
              <div className={`mt-2 text-2xl font-semibold ${metricTone(metric.tone)}`}>{metric.value}</div>
            </div>
          ))}
        </div>
      </section>

      {!data.schemaReady ? (
        <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4 text-sm text-slate-300">
          Customer Success is ready to collect live records. Once customers report projects or usage events arrive, this dashboard will update automatically.
        </div>
      ) : null}
      {message ? <div className="rounded-xl border border-emerald-400/30 bg-emerald-500/10 p-3 text-sm text-emerald-100">{message}</div> : null}
      {error ? <div className="rounded-xl border border-red-400/30 bg-red-500/10 p-3 text-sm text-red-100">{error}</div> : null}

      <section className="rounded-2xl border border-white/10 bg-slate-950 p-4">
        <div className="grid gap-3 lg:grid-cols-[180px_180px_1fr_auto]">
          <select value={range} onChange={event => setRange(event.target.value)} className="studio-input">
            <option value="today">Today</option>
            <option value="yesterday">Yesterday</option>
            <option value="last_7_days">Last 7 days</option>
            <option value="last_30_days">Last 30 days</option>
            <option value="this_month">This month</option>
            <option value="last_month">Last month</option>
            <option value="this_quarter">This quarter</option>
            <option value="this_year">This year</option>
            <option value="all">All time</option>
          </select>
          <select value={statusFilter} onChange={event => setStatusFilter(event.target.value)} className="studio-input">
            <option value="all">All project statuses</option>
            <option value="pending_review">Pending Review</option>
            <option value="verified">Verified</option>
            <option value="rejected">Rejected</option>
          </select>
          <input value={customerFilter} onChange={event => setCustomerFilter(event.target.value)} placeholder="Search customer, email, workspace..." className="studio-input" />
          <button type="button" onClick={() => router.refresh()} className="studio-button"><RefreshCw size={16} /> Refresh</button>
        </div>
      </section>

      <section className="grid gap-4 lg:grid-cols-2">
        <AdminLineChart title="Monthly Verified Revenue" data={data.charts.monthlyRevenue} />
        <AdminLineChart title="Weekly Verified Revenue" data={data.charts.weeklyRevenue} />
        <AdminLineChart title="Daily Usage Seconds" data={data.charts.dailyUsage} />
        <AdminLineChart title="Daily Progress Score" data={data.charts.dailyProgress} />
        <AdminBarChart title="Feature Usage" data={data.charts.featureUsage} />
        <Leaderboard title="Customer Leaderboard" customers={data.leaderboard.highestRevenue} value={customer => money(customer.totalRevenue)} />
      </section>

      <section className="grid gap-4 xl:grid-cols-[1.4fr_1fr]">
        <ProjectReviewQueue projects={filteredProjects} canManage={canManage} loading={isPending} onReview={reviewProject} />
        <CustomerHealthPanel customers={data.customers} />
      </section>

      <section className="grid gap-4 xl:grid-cols-[1fr_1fr]">
        <ActivityTimeline items={data.activityTimeline} />
        <DailyProgressTable rows={data.progressRows} />
      </section>

      <section className="grid gap-4 lg:grid-cols-3">
        <Leaderboard title="Highest Revenue Customer" customers={data.leaderboard.highestRevenue} value={customer => money(customer.totalRevenue)} />
        <Leaderboard title="Most Projects Won" customers={data.leaderboard.mostProjects} value={customer => `${customer.verifiedProjects} projects`} />
        <Leaderboard title="Most Active Customer" customers={data.leaderboard.mostActive} value={customer => duration(customer.totalUsageSeconds)} />
      </section>

      {projectFormOpen ? (
        <ProjectForm
          form={form}
          customers={data.customers}
          saving={isPending}
          onChange={setForm}
          onClose={() => setProjectFormOpen(false)}
          onSubmit={submitProject}
        />
      ) : null}
    </div>
  );
}

function ProjectReviewQueue({ projects, canManage, loading, onReview }: { projects: SuccessProject[]; canManage: boolean; loading: boolean; onReview: (project: SuccessProject, status: ProjectStatus) => void }) {
  return (
    <section className="rounded-2xl border border-white/10 bg-slate-950 p-4">
      <PanelHeader title="Project Review Queue" body="Verified projects feed revenue analytics. Pending and rejected projects remain visible for audit." />
      <div className="mt-4 overflow-x-auto rounded-xl border border-white/10">
        <table className="w-full min-w-[980px] text-left text-sm">
          <thead className="bg-white/[0.04] text-xs uppercase tracking-wide text-slate-400">
            <tr>{["Customer", "Project", "Category", "Date Won", "Value", "Status", "Actions"].map(label => <th key={label} className="px-3 py-3">{label}</th>)}</tr>
          </thead>
          <tbody>
            {projects.map(project => (
              <tr key={project.id} className="border-t border-white/10 align-top">
                <td className="px-3 py-3">
                  <div className="font-semibold text-white">{project.customerName}</div>
                  <div className="text-xs text-slate-500">{project.customerEmail || project.workspaceName}</div>
                </td>
                <td className="px-3 py-3">
                  <div className="font-medium text-slate-100">{project.projectTitle}</div>
                  <div className="text-xs text-slate-500">{project.clientName}</div>
                </td>
                <td className="px-3 py-3">{project.projectCategory}</td>
                <td className="px-3 py-3">{project.dateWon || "-"}</td>
                <td className="px-3 py-3">{money(project.projectValue, project.currency || "USD")}</td>
                <td className="px-3 py-3"><StatusBadge status={project.status} /></td>
                <td className="px-3 py-3">
                  {canManage ? (
                    <div className="flex flex-wrap gap-2">
                      <button disabled={loading} onClick={() => onReview(project, "verified")} className="studio-button border-emerald-400/30 text-emerald-200"><CheckCircle2 size={14} /> Verify</button>
                      <button disabled={loading} onClick={() => onReview(project, "rejected")} className="studio-button border-red-400/30 text-red-200"><XCircle size={14} /> Reject</button>
                    </div>
                  ) : <span className="text-xs text-slate-500">View only</span>}
                </td>
              </tr>
            ))}
            {!projects.length ? <tr><td colSpan={7} className="h-40 text-center text-sm text-slate-500">No project reports match this view.</td></tr> : null}
          </tbody>
        </table>
      </div>
    </section>
  );
}

function CustomerHealthPanel({ customers }: { customers: CustomerSuccessSummary[] }) {
  return (
    <section className="rounded-2xl border border-white/10 bg-slate-950 p-4">
      <PanelHeader title="Customer Health Scores" body="Health uses login frequency, feature usage, session duration, revenue generated, project success, and daily consistency." />
      <div className="mt-4 space-y-3">
        {customers.slice(0, 8).map(customer => (
          <div key={customer.key} className="rounded-xl border border-white/10 bg-white/[0.03] p-3">
            <div className="flex items-center justify-between gap-3">
              <div>
                <div className="font-semibold text-white">{customer.customerName}</div>
                <div className="text-xs text-slate-500">{customer.workspaceName}</div>
              </div>
              <HealthBadge status={customer.healthStatus} score={customer.healthScore} />
            </div>
            <div className="mt-3 grid grid-cols-3 gap-2 text-xs text-slate-400">
              <span>{money(customer.totalRevenue)} revenue</span>
              <span>{customer.verifiedProjects} projects</span>
              <span>{duration(customer.totalUsageSeconds)} used</span>
            </div>
          </div>
        ))}
        {!customers.length ? <EmptyState text="No customer usage or project data yet." /> : null}
      </div>
    </section>
  );
}

function ActivityTimeline({ items }: { items: CustomerSuccessDashboardData["activityTimeline"] }) {
  return (
    <section className="rounded-2xl border border-white/10 bg-slate-950 p-4">
      <PanelHeader title="Customer Timeline" body="Event-based tracking of logins, edits, AI usage, publishing, outreach, and exports." />
      <div className="mt-4 space-y-3">
        {items.slice(0, 14).map(item => (
          <div key={item.id} className="flex gap-3 rounded-xl border border-white/10 bg-white/[0.03] p-3">
            <div className="mt-1 h-2 w-2 rounded-full bg-emerald-400" />
            <div>
              <div className="text-sm font-medium text-white">{item.eventLabel || item.eventType}</div>
              <div className="text-xs text-slate-500">{formatDate(item.occurredAt)} · {item.customerName} · {item.moduleKey || "platform"}</div>
            </div>
          </div>
        ))}
        {!items.length ? <EmptyState text="No customer timeline events yet." /> : null}
      </div>
    </section>
  );
}

function DailyProgressTable({ rows }: { rows: CustomerSuccessDashboardData["progressRows"] }) {
  return (
    <section className="rounded-2xl border border-white/10 bg-slate-950 p-4">
      <PanelHeader title="Daily Progress Tracking" body="Daily totals for blogs, pages, campaigns, AI, leads, knowledge, SEO, outreach, and uploads." />
      <div className="mt-4 overflow-x-auto rounded-xl border border-white/10">
        <table className="w-full min-w-[860px] text-left text-sm">
          <thead className="bg-white/[0.04] text-xs uppercase tracking-wide text-slate-400">
            <tr>{["Customer", "Date", "Blogs", "Pages", "Campaigns", "AI", "Leads", "SEO", "Outreach", "Score"].map(label => <th key={label} className="px-3 py-3">{label}</th>)}</tr>
          </thead>
          <tbody>
            {rows.slice(0, 12).map(row => (
              <tr key={row.id} className="border-t border-white/10">
                <td className="px-3 py-3">{row.customerName}</td>
                <td className="px-3 py-3">{row.progressDate}</td>
                <td className="px-3 py-3">{row.blogsPublished}</td>
                <td className="px-3 py-3">{row.pagesEdited}</td>
                <td className="px-3 py-3">{row.campaignsCreated}</td>
                <td className="px-3 py-3">{row.aiCreditsUsed}</td>
                <td className="px-3 py-3">{row.leadsAdded}</td>
                <td className="px-3 py-3">{row.seoTasksCompleted}</td>
                <td className="px-3 py-3">{row.outreachActivities}</td>
                <td className="px-3 py-3">{row.productivityScore}</td>
              </tr>
            ))}
            {!rows.length ? <tr><td colSpan={10} className="h-40 text-center text-sm text-slate-500">No daily progress records yet.</td></tr> : null}
          </tbody>
        </table>
      </div>
    </section>
  );
}

function Leaderboard({ title, customers, value }: { title: string; customers: CustomerSuccessSummary[]; value: (customer: CustomerSuccessSummary) => string }) {
  return (
    <section className="rounded-2xl border border-white/10 bg-slate-950 p-4">
      <PanelHeader title={title} body="Ranked from live customer success and usage data." />
      <div className="mt-4 space-y-3">
        {customers.slice(0, 6).map((customer, index) => (
          <div key={customer.key} className="flex items-center justify-between gap-3 rounded-xl border border-white/10 bg-white/[0.03] p-3">
            <div className="flex items-center gap-3">
              <div className="flex h-8 w-8 items-center justify-center rounded-full bg-blue-500 text-xs font-semibold text-white">{index + 1}</div>
              <div>
                <div className="font-semibold text-white">{customer.customerName}</div>
                <div className="text-xs text-slate-500">{customer.customerEmail || customer.workspaceName}</div>
              </div>
            </div>
            <div className="text-sm font-semibold text-emerald-200">{value(customer)}</div>
          </div>
        ))}
        {!customers.length ? <EmptyState text="No leaderboard data yet." /> : null}
      </div>
    </section>
  );
}

function ProjectForm({ form, customers, saving, onChange, onClose, onSubmit }: { form: typeof defaultProjectForm; customers: CustomerSuccessSummary[]; saving: boolean; onChange: (form: typeof defaultProjectForm) => void; onClose: () => void; onSubmit: () => void }) {
  function chooseCustomer(key: string) {
    const customer = customers.find(item => item.key === key);
    if (!customer) return;
    onChange({ ...form, userId: customer.userId, workspaceId: customer.workspaceId });
  }

  return (
    <div className="fixed inset-0 z-50 bg-black/70">
      <aside className="ml-auto h-full w-full max-w-2xl overflow-y-auto border-l border-white/10 bg-slate-950 p-6">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-xl font-semibold text-white">Report New Project</h2>
            <p className="mt-1 text-sm text-slate-400">Submitted projects enter Pending Review until an admin verifies them.</p>
          </div>
          <button onClick={onClose} className="studio-button">Close</button>
        </div>
        <div className="mt-5 grid gap-4">
          <label className="block">
            <span className="text-xs font-medium text-slate-400">Customer</span>
            <select onChange={event => chooseCustomer(event.target.value)} className="studio-input mt-1" defaultValue="">
              <option value="">Select customer workspace</option>
              {customers.map(customer => <option key={customer.key} value={customer.key}>{customer.customerName} · {customer.workspaceName}</option>)}
            </select>
          </label>
          <Input label="Client Name" value={form.clientName} onChange={value => onChange({ ...form, clientName: value })} />
          <Input label="Project Title" value={form.projectTitle} onChange={value => onChange({ ...form, projectTitle: value })} />
          <Input label="Lead Source (Optional)" value={form.leadSource} onChange={value => onChange({ ...form, leadSource: value })} />
          <Input label="Project Category" value={form.projectCategory} onChange={value => onChange({ ...form, projectCategory: value })} />
          <TextArea label="Project Description" value={form.projectDescription} onChange={value => onChange({ ...form, projectDescription: value })} />
          <div className="grid gap-4 sm:grid-cols-3">
            <Input label="Date Won" type="date" value={form.dateWon} onChange={value => onChange({ ...form, dateWon: value })} />
            <Input label="Currency" value={form.currency} onChange={value => onChange({ ...form, currency: value.toUpperCase().slice(0, 3) })} />
            <Input label="Project Value" type="number" value={form.projectValue} onChange={value => onChange({ ...form, projectValue: value })} />
          </div>
          <label className="flex items-center gap-2 text-sm text-slate-300">
            <input type="checkbox" checked={form.isRecurringRevenue} onChange={event => onChange({ ...form, isRecurringRevenue: event.target.checked })} className="h-4 w-4 accent-emerald-500" />
            Is this recurring revenue?
          </label>
          <TextArea label="Notes" value={form.notes} onChange={value => onChange({ ...form, notes: value })} />
          <Input label="Invoice or Screenshot URL (Optional)" value={form.invoiceUrl} onChange={value => onChange({ ...form, invoiceUrl: value })} />
        </div>
        <div className="mt-6 flex justify-end gap-2">
          <button onClick={onClose} className="studio-button">Cancel</button>
          <button disabled={saving} onClick={onSubmit} className="studio-button bg-emerald-500 text-slate-950 hover:bg-emerald-400">Submit Project</button>
        </div>
      </aside>
    </div>
  );
}

function ExportButton({ format }: { format: "csv" | "xls" | "pdf" }) {
  return <a href={`/api/admin/customer-success/export?format=${format}`} className="studio-button"><Download size={16} /> {format.toUpperCase()}</a>;
}

function PanelHeader({ title, body }: { title: string; body: string }) {
  return <div><h2 className="text-xl font-semibold text-white">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-400">{body}</p></div>;
}

function Input({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) {
  return <label className="block"><span className="text-xs font-medium text-slate-400">{label}</span><input type={type} value={value} onChange={event => onChange(event.target.value)} className="studio-input mt-1" /></label>;
}

function TextArea({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) {
  return <label className="block"><span className="text-xs font-medium text-slate-400">{label}</span><textarea value={value} onChange={event => onChange(event.target.value)} rows={4} className="studio-input mt-1" /></label>;
}

function StatusBadge({ status }: { status: ProjectStatus }) {
  const styles = {
    pending_review: "bg-amber-500/10 text-amber-200 ring-amber-400/20",
    verified: "bg-emerald-500/10 text-emerald-200 ring-emerald-400/20",
    rejected: "bg-red-500/10 text-red-200 ring-red-400/20"
  };
  return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ${styles[status]}`}>{readable(status)}</span>;
}

function HealthBadge({ status, score }: { status: string; score: number }) {
  const styles = status === "Healthy" ? "bg-emerald-500/10 text-emerald-200 ring-emerald-400/20" : status === "Moderate" ? "bg-amber-500/10 text-amber-200 ring-amber-400/20" : "bg-red-500/10 text-red-200 ring-red-400/20";
  return <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ${styles}`}><ShieldAlert size={13} /> {status} {score}</span>;
}

function EmptyState({ text }: { text: string }) {
  return <div className="rounded-xl border border-dashed border-white/10 p-6 text-center text-sm text-slate-500">{text}</div>;
}

function metricTone(tone?: "blue" | "green" | "amber" | "red" | "slate") {
  if (tone === "green") return "text-emerald-200";
  if (tone === "amber") return "text-amber-200";
  if (tone === "red") return "text-red-200";
  if (tone === "blue") return "text-blue-200";
  return "text-slate-100";
}

function rangeDate(range: string) {
  const now = new Date();
  if (range === "all") return null;
  if (range === "today") return startOfToday(now);
  if (range === "yesterday") {
    const date = startOfToday(now);
    date.setDate(date.getDate() - 1);
    return date;
  }
  if (range === "last_7_days") return daysAgo(7);
  if (range === "last_30_days") return daysAgo(30);
  if (range === "this_month") {
    const date = new Date(now);
    date.setDate(1);
    date.setHours(0, 0, 0, 0);
    return date;
  }
  if (range === "last_month") {
    const date = new Date(now.getFullYear(), now.getMonth() - 1, 1);
    return date;
  }
  if (range === "this_quarter") {
    const quarterStart = Math.floor(now.getMonth() / 3) * 3;
    return new Date(now.getFullYear(), quarterStart, 1);
  }
  if (range === "this_year") return new Date(now.getFullYear(), 0, 1);
  return daysAgo(30);
}

function startOfToday(date: Date) {
  const clone = new Date(date);
  clone.setHours(0, 0, 0, 0);
  return clone;
}

function daysAgo(days: number) {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000);
}

function readable(value: string) {
  return value.replace(/_/g, " ").replace(/^./, character => character.toUpperCase());
}

function formatDate(value: string) {
  if (!value) return "-";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "-";
  return new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(date);
}
